#!/usr/bin/env bash
# PreToolUse hook: block commits and PRs containing AI attribution.
# Rejects any Bash command that includes Co-Authored-By, Claude, AI assistant,
# or similar references in git commit or gh pr create invocations.

set -euo pipefail

# Read the tool input from stdin
INPUT=$(cat)

# Extract the command being run
COMMAND=$(echo "$INPUT" | grep -o '"command":"[^"]*"' | head -1 | sed 's/"command":"//;s/"$//' || true)

if [ -z "$COMMAND" ]; then
  exit 0
fi

# Only check git commit and gh pr create commands
IS_GIT_COMMIT=$(echo "$COMMAND" | grep -ci 'git commit' || true)
IS_GH_PR=$(echo "$COMMAND" | grep -ci 'gh pr create' || true)

if [ "$IS_GIT_COMMIT" -eq 0 ] && [ "$IS_GH_PR" -eq 0 ]; then
  exit 0
fi

# Block AI attribution patterns
HAS_COAUTHORED=$(echo "$COMMAND" | grep -ci 'Co-Authored-By' || true)
HAS_CLAUDE=$(echo "$COMMAND" | grep -ci 'claude' || true)
HAS_AI_ASSISTANT=$(echo "$COMMAND" | grep -ci 'ai assistant\|ai-generated\|generated by' || true)
HAS_ANTHROPIC=$(echo "$COMMAND" | grep -ci 'anthropic\|noreply@anthropic' || true)

if [ "$HAS_COAUTHORED" -gt 0 ] || [ "$HAS_CLAUDE" -gt 0 ] || [ "$HAS_AI_ASSISTANT" -gt 0 ] || [ "$HAS_ANTHROPIC" -gt 0 ]; then
  echo "BLOCKED: Commit/PR message contains AI attribution (Co-Authored-By, Claude, Anthropic, etc.)." >&2
  echo "Remove all AI references from the message before committing." >&2
  exit 2
fi

exit 0
