/**
 * @file index.ts
 * @module types/index
 *
 * Barrel re-exports for all shared type definitions.
 * Import strictly from `@/types` instead of reaching directly into individual modules to prevent circular dependencies.
 */

export type {
  AlgorithmCategory,
  AlgorithmDefinition,
  AlgorithmMeta,
  ComplexitySpec,
  SupportedLanguage,
} from "./algorithm";

export type { EducationalContent } from "./educational";

export type {
  ArrayElement,
  ArrayElementState,
  ArrayVisualState,
  DPCell,
  DPCellState,
  DPTableVisualState,
  ExecutionStep,
  GraphEdge,
  GraphEdgeState,
  GraphNode,
  GraphNodeState,
  GraphVisualState,
  GridCell,
  GridCellState,
  GridCellType,
  GridVisualState,
  LineHighlight,
  StepMetrics,
  StepType,
  TreeNode,
  TreeNodeState,
  TreeVisualState,
  LinkedListNode,
  LinkedListNodeState,
  LinkedListVisualState,
  HeapNode,
  HeapNodeState,
  HeapVisualState,
  StackElement,
  StackElementState,
  InputChar,
  InputCharState,
  NumericInputState,
  NumericInputElement,
  OutputElementState,
  OutputElement,
  ResultElementState,
  ResultElement,
  CircularBufferState,
  StackQueueVisualState,
  HashMapEntry,
  HashMapEntryState,
  HashMapInputElement,
  HashMapInputElementState,
  HashMapVisualState,
  StringChar,
  StringCharState,
  FailureTableEntry,
  FailureTableEntryState,
  StringVisualState,
  PalindromeVisualState,
  FrequencyEntryState,
  FrequencyEntry,
  FrequencyVisualState,
  TransformVisualState,
  TrieNodeState,
  TrieEdgeState,
  TrieNode,
  TrieEdge,
  TrieVisualState,
  DistanceCellState,
  DistanceCell,
  EditOperation,
  DistanceVisualState,
  MatrixCell,
  MatrixCellState,
  MatrixBoundaries,
  MatrixSearchRegion,
  SpiralDirection,
  MatrixTraversalDirection,
  MatrixVisualState,
  SetElement,
  SetElementState,
  SetPhase,
  SetVisualState,
  VisualState,
} from "./execution";
