import type { EducationalContent } from "@/types";

export const generateBinaryNumbersEducational: EducationalContent = {
  overview:
    "**Generate Binary Numbers** produces the binary representations of all integers from 1 to N in order. Instead of converting each number individually, the algorithm exploits the structural relationship between binary strings: appending `'0'` or `'1'` to a binary string produces the next two numbers in the BFS-level traversal of the binary tree of representations.\n\nA queue drives the process — seed it with `'1'`, then repeatedly dequeue the front element, record it, and enqueue two children with `'0'` and `'1'` appended.",

  howItWorks:
    "The algorithm treats binary strings as nodes in a full binary tree, visited level by level:\n\n" +
    "1. **Initialize** — enqueue the string `'1'` as the root.\n" +
    "2. **Repeat N times:**\n" +
    "   - **Dequeue** the front string — this is the next binary number in sequence.\n" +
    "   - **Record** it in the result array.\n" +
    "   - **Enqueue** `current + '0'` (left child).\n" +
    "   - **Enqueue** `current + '1'` (right child).\n" +
    "3. **Return** the result array after N iterations.\n\n" +
    "### Example trace for N = 5\n\n" +
    "```\n" +
    "Step  Dequeue  Enqueue        Queue after\n" +
    "0     '1'      '10', '11'     ['10', '11']\n" +
    "1     '10'     '100', '101'   ['11', '100', '101']\n" +
    "2     '11'     '110', '111'   ['100', '101', '110', '111']\n" +
    "3     '100'    '1000', '1001' ['101', '110', '111', '1000', '1001']\n" +
    "4     '101'    '1010', '1011' ['110', '111', '1000', '1001', '1010', '1011']\n" +
    "Result: ['1', '10', '11', '100', '101']\n" +
    "```",

  timeAndSpaceComplexity:
    "**Time Complexity: `O(n)`**\n\n" +
    "Each of the N iterations performs exactly one dequeue and two enqueues — all `O(1)` queue operations. The total work is linear in N.\n\n" +
    "**Space Complexity: `O(n)`**\n\n" +
    "The result array holds N strings. The queue holds at most `O(n)` strings at any point (the frontier of the binary tree at the current level), so space is also `O(n)` overall.",

  bestAndWorstCase:
    "**Best case** — N = 1: a single dequeue and two enqueues, completing in `O(1)` effective work.\n\n" +
    "**Worst case** — N is large: all N iterations run, with the queue growing as deeper binary tree levels are explored. Both time and space scale linearly at `O(n)`.\n\n" +
    "There is no early-exit condition — the algorithm always runs exactly N iterations.",

  realWorldUses: [
    "**Huffman coding:** Binary prefix codes are generated by traversing a binary tree with the same left-child ('0') / right-child ('1') pattern.",
    "**Binary counter circuits:** Hardware counters use the same structural rule — each bit pattern naturally follows from its parent by appending 0 or 1.",
    "**BFS-order enumeration:** Any problem requiring level-by-level traversal of a binary structure (e.g., printing all N-bit strings in lexicographic order) uses the same queue pattern.",
    "**Data encoding tests:** Generating sequential binary strings is useful for testing encoders, decoders, and binary protocol parsers against known inputs.",
  ],

  strengthsAndLimitations: {
    strengths: [
      "O(n) time — no repeated string conversion or division operations.",
      "Produces results in correct ascending numerical order naturally.",
      "Simple and readable — the queue structure mirrors the binary tree conceptually.",
      "Easily extended to generate binary strings of a fixed length by stopping at a given depth.",
    ],
    limitations: [
      "O(n) queue space — the frontier grows as deeper tree levels are reached.",
      "Strings grow in length as N increases — memory per element is O(log n) bits.",
      "For very large N, total memory for all strings is O(n log n) due to string lengths.",
      "Not suitable when you need only one specific binary number — direct conversion is faster.",
    ],
  },

  whenToUseIt:
    "Use the queue-based BFS approach when you need all binary representations from 1 to N in order and want to avoid repeated integer division or bit manipulation. If you only need the binary representation of a single number, use the built-in `toString(2)` or equivalent. For generating all N-bit strings (fixed width), consider a simple counter with zero-padding instead.",
};
