import type { EducationalContent } from "@/types";

export const toeplitzMatrixEducational: EducationalContent = {
  overview:
    "A **Toeplitz Matrix** is a matrix in which every descending diagonal from the upper-left to the lower-right " +
    "contains all identical values. Formally, `matrix[rowIdx][colIdx] == matrix[rowIdx-1][colIdx-1]` for all valid positions.\n\n" +
    "This verification problem (LeetCode 766) checks whether a given matrix satisfies the Toeplitz property by comparing " +
    "each interior cell with its upper-left neighbor — a single O(m × n) pass with no extra memory.",

  howItWorks:
    "The algorithm iterates over every cell in the matrix that has an upper-left neighbor — i.e., every cell " +
    "at row `rowIdx ≥ 1` and column `colIdx ≥ 1`. For each such cell:\n\n" +
    "1. Read `current = matrix[rowIdx][colIdx]`.\n" +
    "2. Read `upperLeft = matrix[rowIdx-1][colIdx-1]`.\n" +
    "3. If `current ≠ upperLeft`, the diagonal is broken — return `false` immediately.\n\n" +
    "If all comparisons pass, the matrix is Toeplitz — return `true`.\n\n" +
    "### Example (Toeplitz)\n\n" +
    "```\n" +
    "1  2  3  4\n" +
    "5  1  2  3\n" +
    "9  5  1  2\n" +
    "```\n\n" +
    "Every diagonal: `[1,1,1]`, `[2,2,2]`, `[3,3]`, `[4]`, `[5,5]`, `[9]` — all uniform. Result: `true`.\n\n" +
    "### Counter-example (not Toeplitz)\n\n" +
    "```\n" +
    "1  2\n" +
    "2  2\n" +
    "```\n\n" +
    "`matrix[1][1] = 2 ≠ matrix[0][0] = 1` — Result: `false`.\n\n" +
    "### Diagram: verifying a 3 × 4 Toeplitz matrix\n\n" +
    "```mermaid\n" +
    "flowchart TD\n" +
    '  subgraph Row0["Row 0"]\n' +
    '    R0C0["1"] --- R0C1["2"] --- R0C2["3"] --- R0C3["4"]\n' +
    "  end\n" +
    '  subgraph Row1["Row 1"]\n' +
    '    R1C0["5"] --- R1C1["1"] --- R1C2["2"] --- R1C3["3"]\n' +
    "  end\n" +
    '  subgraph Row2["Row 2"]\n' +
    '    R2C0["9"] --- R2C1["5"] --- R2C2["1"] --- R2C3["2"]\n' +
    "  end\n" +
    '  R0C0 -->|"== ?"| R1C1\n' +
    '  R1C1 -->|"== ?"| R2C2\n' +
    "  style R0C0 fill:#06b6d4,stroke:#0891b2\n" +
    "  style R1C1 fill:#f59e0b,stroke:#d97706\n" +
    "  style R2C2 fill:#14532d,stroke:#22c55e\n" +
    "```\n\n" +
    "Each cell is compared with its upper-left neighbor along the same diagonal; cyan is the diagonal origin, amber is the cell under check, green confirms a match.",

  timeAndSpaceComplexity:
    "**Time Complexity: `O(m × n)`**\n\n" +
    "Every cell except the first row and first column is compared exactly once against its upper-left neighbor. " +
    "That is `(m-1) × (n-1)` comparisons — asymptotically `O(m × n)`.\n\n" +
    "**Space Complexity: `O(1)`**\n\n" +
    "Only two temporary variables (`current`, `upperLeft`) are used per comparison. No auxiliary data structures required.",

  bestAndWorstCase:
    "**Best case** — first interior cell fails the diagonal check: the algorithm returns `false` immediately after one comparison, `O(1)` effective.\n\n" +
    "**Worst case** — the matrix is Toeplitz or the last interior cell is the only mismatch: all `(m-1)(n-1)` comparisons are made, `O(m × n)`.\n\n" +
    "Special shapes: a 1×1, single-row, or single-column matrix is trivially Toeplitz (no interior cells to compare), " +
    "so the loop body never executes and the result is immediately `true`.",

  realWorldUses: [
    "**Signal processing:** Toeplitz matrices arise naturally in convolution and correlation computations, making fast Toeplitz solvers critical for audio/image filtering.",
    "**Linear algebra libraries:** Verifying the Toeplitz property before applying specialized O(n log n) Toeplitz solvers (vs. generic O(n³) Gaussian elimination).",
    "**Data validation:** Checking that generated or received matrices meet structural invariants in scientific computing pipelines.",
    "**Compiler / theorem prover verification:** Structural matrix properties are used as preconditions in formally verified numerical algorithms.",
  ],

  strengthsAndLimitations: {
    strengths: [
      "O(m × n) time — optimal since every cell must be inspected at least once.",
      "O(1) extra space — no auxiliary arrays, maps, or recursion stacks.",
      "Early exit on first mismatch reduces average-case work significantly.",
      "Simple, readable logic with a single nested loop and one comparison per cell.",
    ],
    limitations: [
      "Only verifies — does not construct a Toeplitz matrix or repair a near-Toeplitz one.",
      "Cannot handle jagged (non-rectangular) matrices without additional row-length checks.",
      "For very large sparse matrices, a diagonal-indexed storage format would be more efficient than full traversal.",
    ],
  },

  whenToUseIt:
    "Use this check whenever a matrix is expected to be Toeplitz before applying a specialized Toeplitz algorithm " +
    "(such as the Levinson recursion or fast Toeplitz matrix-vector multiplication). For matrices generated by convolution " +
    "kernels or shift-invariant operations, the Toeplitz property is guaranteed analytically — the check is only needed " +
    "when the matrix arrives from an external source and must be validated.",
};
